### ISSUE TITLE
Fatal errors when switching roles

### ISSUE THREAD

**Issue by ewallah** [FMCorz/moodle-block_stash#1]
As an admin, when I try to switch roles to a student, I get a fatal error: Class 'block_stash\required_capability_exception' not found in /var/www/moodle3/blocks/stash/classes/manager.php on line 665

Fatal errors put a site down. Perhaps the maturity of this plugin should be rc?

(Moodle 3.1)

**Comment by FMCorz** [comment]
Thanks for reporting this. Switching role is an edge case that I didn't think of. Now, to be honest, I did not expect anyone to try the plugin just yet, I only made it public today. How did you find out about it?

**Comment by ewallah** [comment]
Your Github repository is public,  so it is listed in the recent changes:
https://github.com/search?q=moodle&type=Repositories&s=updated
