### ISSUE TITLE
Stash in Moodle 3.2 and Boost

### ISSUE THREAD

**Issue by kannakr** [FMCorz/moodle-block_stash#12]
Hello developers, 

This is to mention that Stash looks bit odd with Boost theme in Moodle 3.2. 
Specifically the Supplies option appears twice (before and after save button), in the Add a new location page.

Here is a screenshot:

![stash](https://cloud.githubusercontent.com/assets/16013187/21306270/cb799166-c5d8-11e6-8de7-2d4bf1c95a4d.png)

It worth mention that still works fine.
Anna

**Comment by FMCorz** [comment]
Thanks. This has been fixed. It will be part of the next release.
