### ISSUE TITLE
bug create items

### ISSUE THREAD

**Issue by KvardeKvar** [FMCorz/moodle-block_stash#15]
Hello good plugin authors
When you create an element (items) gives the following error **

Sorry for my English.

Moodle 3.2+ (Build: 20161215)
PHP Version 5.6.30

**
Function createElement() can not be called statically, this will no longer work in PHP 7.1

    line 555 of /lib/pear/HTML/QuickForm.php: call to debugging()
    line 77 of /blocks/stash/classes/form/integer.php: call to HTML_QuickForm->createElement()
    line 546 of /lib/pear/HTML/QuickForm/group.php: call to block_stash_form_integer->_createElements()
    line 163 of /lib/pear/HTML/QuickForm/group.php: call to HTML_QuickForm_group->_createElementsIfNotExist()
    line 132 of /blocks/stash/classes/form/integer.php: call to HTML_QuickForm_group->setValue()
    line 382 of /lib/pear/HTML/QuickForm/element.php: call to block_stash_form_integer->onQuickFormEvent()
    line 417 of /lib/pear/HTML/QuickForm/group.php: call to HTML_QuickForm_element->onQuickFormEvent()
    line 144 of /lib/form/group.php: call to HTML_QuickForm_group->onQuickFormEvent()
    line 142 of /blocks/stash/classes/form/integer.php: call to MoodleQuickForm_group->onQuickFormEvent()
    line 592 of /lib/pear/HTML/QuickForm.php: call to block_stash_form_integer->onQuickFormEvent()
    line 622 of /lib/pear/HTML/QuickForm.php: call to HTML_QuickForm->_loadElement()
    line 91 of /blocks/stash/classes/form/drop.php: call to HTML_QuickForm->addElement()
    line 204 of /lib/formslib.php: call to block_stash\form\drop->definition()
    line 109 of /admin/tool/lp/classes/form/persistent.php: call to moodleform->__construct()
    line 51 of /blocks/stash/drop.php: call to tool_lp\form\persistent->__construct()

Function createElement() can not be called statically, this will no longer work in PHP 7.1

    line 555 of /lib/pear/HTML/QuickForm.php: call to debugging()
    line 83 of /blocks/stash/classes/form/integer.php: call to HTML_QuickForm->createElement()
    line 546 of /lib/pear/HTML/QuickForm/group.php: call to block_stash_form_integer->_createElements()
    line 163 of /lib/pear/HTML/QuickForm/group.php: call to HTML_QuickForm_group->_createElementsIfNotExist()
    line 132 of /blocks/stash/classes/form/integer.php: call to HTML_QuickForm_group->setValue()
    line 382 of /lib/pear/HTML/QuickForm/element.php: call to block_stash_form_integer->onQuickFormEvent()
    line 417 of /lib/pear/HTML/QuickForm/group.php: call to HTML_QuickForm_element->onQuickFormEvent()
    line 144 of /lib/form/group.php: call to HTML_QuickForm_group->onQuickFormEvent()
    line 142 of /blocks/stash/classes/form/integer.php: call to MoodleQuickForm_group->onQuickFormEvent()
    line 592 of /lib/pear/HTML/QuickForm.php: call to block_stash_form_integer->onQuickFormEvent()
    line 622 of /lib/pear/HTML/QuickForm.php: call to HTML_QuickForm->_loadElement()
    line 91 of /blocks/stash/classes/form/drop.php: call to HTML_QuickForm->addElement()
    line 204 of /lib/formslib.php: call to block_stash\form\drop->definition()
    line 109 of /admin/tool/lp/classes/form/persistent.php: call to moodleform->__construct()
    line 51 of /blocks/stash/drop.php: call to tool_lp\form\persistent->__construct()

**Comment by abgreeve** [comment]
Hello KvardeKvar,

Thank you for the report. We have a fix for this issue which will be in the next version.
