### ISSUE TITLE
Block "Stash" in course categories

### ISSUE THREAD

**Issue by abkoch** [FMCorz/moodle-block_stash#26]
Dear developer,

thanks for your great gamification plugin.

One tiny issue: It should not be possible for users to add stash blocks to course categories. This leads to an error that makes it impossible to use the concerning category unless the conflicting database entry is deleted.

Best regards
Andreas

**Comment by FMCorz** [comment]
Thanks @abkoch. The plugin is currently maintained elsewhere, we rmoved your report there:
https://github.com/abgreeve/moodle-block_stash/issues/21

**Comment by abkoch** [comment]
Thanks @FMCorz.
