### ISSUE TITLE
Exception thrown after has been removed

### ISSUE THREAD

**Issue by mudrd8mz** [FMCorz/moodle-block_stash#7]
I removed the block instance from the course while I left some dropped items in the course. When the filter is about to render the dropped item, it throws exception because of `require_enabled()`. I would expect that in this case, the forgotten drop is simply ignored and an empty string is rendered in its place (or maybe some warning). Thrown exception just does not look appropriate in this case.

```
The stash is not enabled. Was the block added to the course?

More information about this error

Debug info: Error code: stashdisabled

Stack trace:
line 685 of /blocks/stash/classes/manager.php: moodle_exception thrown
line 364 of /blocks/stash/classes/manager.php: call to block_stash\manager->require_enabled()
line 169 of /filter/stash/filter.php: call to block_stash\manager->get_drop()
line 81 of /filter/stash/filter.php: call to filter_stash->transform_shortcode()
line 176 of /lib/filterlib.php: call to filter_stash->filter()
line 218 of /lib/filterlib.php: call to filter_manager->apply_filter_chain()
line 335 of /lib/filterlib.php: call to filter_manager->filter_text()
line 1269 of /lib/weblib.php: call to performance_measuring_filter_manager->filter_text()
line 963 of /course/format/renderer.php: call to format_text()
line 230 of /course/format/renderer.php: call to format_section_renderer_base->format_summary_text()
line 897 of /course/format/renderer.php: call to format_section_renderer_base->section_header()
line 56 of /course/format/topics/format.php: call to format_section_renderer_base->print_multiple_section_page()
line 280 of /course/view.php: call to require()
```

**Comment by FMCorz** [comment]
Thanks! I think I'll raise an issue for Moodle as it's too risky to let filters break an entire site. Meantime, I've fixed it in the filter. Cheers!

**Comment by marcovarmat** [comment]
I have the same problem when i insert STASH on the courses page... what can i do ? Please help me ...
![Escondite no habilitado](https://user-images.githubusercontent.com/18476707/88148989-6d420980-cbcd-11ea-8252-e12c85d91b47.PNG)

**Comment by FMCorz** [comment]
HI @marcovarmat, this issue has been closed for 4 years, we should create another one. Having said that, would you please confirm your Moodle and Stash versions?

**Comment by marcovarmat** [comment]
Of course, Moodle 3.9 (Build: 20200615) and Stash 1.3.3 ...

**Comment by marcovarmat** [comment]
I have the problem in course/index.php i accidentally activate stash in that page and then i can't go back...
